// Shared interview-room UI copy, keyed by locale.
// Extracted from the legacy LiveInterviewPage during Phase 1 cleanup so
// AIInterviewRoomPage no longer depends on the deleted legacy page.

export const UI_LABELS = {
  en: {
    loading: 'Loading interview…',
    jobNotFound: 'Job not found. Please go back and try again.',
    backToInterviews: 'Back to Interviews',
    aboutToStart: 'You are about to start a live AI interview. You will answer 6 questions with an optional 15-minute timer. Your camera and microphone will be used. Answers are saved as you go.',
    bullets: [
      '6 AI-generated interview questions',
      'Optional camera and speech recognition',
      'Answers auto-saved to your profile',
      'AI feedback report on completion',
    ],
    savedDraft: 'Saved draft found',
    restore: 'Restore',
    startFresh: '🚀 Start Interview',
    cancel: 'Cancel',
    offline: 'You are offline. Your answers are saved locally and will sync when reconnected.',
    question: 'Question',
    of: 'of',
    yourAnswer: 'Your Answer',
    speakAnswer: 'Speak your answer',
    stopMicrophone: 'Stop speaking',
    chars: 'chars',
    starMethod: 'STAR method guide',
    previous: 'Previous',
    next: 'Next Question',
    finish: 'Finish Interview',
    submitting: 'Submitting…',
    timeRemaining: 'Time remaining',
    progress: 'Progress',
    liveAnalytics: 'Live Analytics',
    words: 'Words', chars2: 'Chars', wpm: 'WPM',
    speaking: 'Speaking', silence: 'Silence', pauses: 'Pauses',
    avgPause: 'Avg Pause', longestPause: 'Longest', avgWpm: 'Avg WPM',
    filler: 'filler', fillerWord: 'word', fillerWords: 'words',
    microphone: 'Microphone', eyeContact: 'Eye Contact', emotion: 'Emotion',
    approxOnly: 'approx. only',
    listenPlaceholder: 'Speak your answer… (stop microphone to type manually)',
    typePlaceholder: 'Type your answer here, or use the microphone button to speak…',
    rec: 'REC',
    characters: 'Characters',
    // Camera
    cameraUnavailable: 'Camera unavailable',
    cameraPaused: 'Camera paused',
    switchCamera: 'Switch camera',
    turnCameraOff: 'Turn camera off',
    turnCameraOn: 'Turn camera on',
    live: 'LIVE',
    // Microphone
    micPermissionDenied: 'Permission denied',
    micNoMicrophone: 'No microphone found',
    micMuted: 'Muted',
    micListening: 'Listening',
    micSpeaking: 'Speaking',
    // Eye contact
    eyeContactOff: 'Eye contact off',
    eyeContactLoading: 'Loading eye contact…',
    lookingForward: 'Looking Forward',
    lookingAway: 'Looking Away',
    lookingLeft: 'Looking Left',
    lookingRight: 'Looking Right',
    lookingDown: 'Looking Down',
    qualityExcellent: 'Excellent',
    qualityGood: 'Good',
    qualityAverage: 'Average',
    qualityPoor: 'Poor',
    eyeContactLabel: 'Eye contact',
    noFace: 'No face',
    multipleFaces: 'Multiple faces',
    notCentred: 'Not centred',
    lookAtCamera: 'Look at camera',
    // Emotion
    emotionOff: 'Emotion off',
    emotionLoading: 'Loading emotion…',
    noFaceDetected: 'No face detected',
    approxVisualCue: 'approx. visual cue only',
    emotionNeutral: 'Neutral', emotionHappy: 'Happy', emotionConfident: 'Confident',
    emotionNervous: 'Nervous', emotionSad: 'Sad', emotionAngry: 'Angry',
    emotionSurprised: 'Surprised', emotionDistracted: 'Distracted', emotionDetecting: 'Detecting…',
    emotionDescNeutral: 'Calm and composed',
    emotionDescHappy: 'Positive and engaged',
    emotionDescConfident: 'Self-assured and clear',
    emotionDescNervous: 'Anxious or unsure',
    emotionDescSad: 'Low energy or discouraged',
    emotionDescAngry: 'Frustrated or tense',
    emotionDescSurprised: 'Caught off guard',
    emotionDescDistracted: 'Unfocused or disengaged',
    // Speech status
    listeningSpeak: 'Listening… speak your answer',
    // STAR
    starSituation: 'Situation', starTask: 'Task', starAction: 'Action', starResult: 'Result',
    // Errors (mapped from error codes)
    errCameraDisconnected: 'Camera disconnected. Attempting to reconnect…',
    errCameraDenied: 'Camera permission denied. Please allow camera access in your browser settings.',
    errCameraNotFound: 'No camera found on this device.',
    errCameraInUse: 'Camera is already in use by another application.',
    errCameraGeneric: 'Failed to access camera.',
    errMicDenied: 'Microphone permission denied.',
    errMicNotFound: 'No microphone found.',
    errMicGeneric: 'Failed to access microphone.',
    errSpeechNoSpeech: 'No speech detected. Please try again.',
    errSpeechAudioCapture: 'No microphone found.',
    errSpeechNetwork: 'Network error. Check your connection.',
    errSpeechNotAllowed: 'Microphone permission denied.',
    errSpeechServiceNotAllowed: 'Speech recognition not allowed.',
    errSpeechLangNotSupported: 'Language not supported.',
    errSpeechAborted: 'Speech recognition aborted.',
    errSpeechMaxRestarts: 'Speech recognition lost connection.',
    errSpeechStartFailed: 'Failed to start microphone access.',
    errEyeContactUnavailable: 'Eye contact detection unavailable.',
    errEmotionUnavailable: 'Emotion detection unavailable.',
    errInitFailed: 'Failed to initialize interview. Please try again.',
    errStartFailed: 'Failed to start interview.',
    errUnexpected: 'An unexpected error occurred during the interview.',
  },
  az: {
    loading: 'Müsahibə yüklənir…',
    jobNotFound: 'İş tapılmadı. Geri qayıdın.',
    backToInterviews: 'Müsahibələrə qayıt',
    aboutToStart: 'Canlı süni intellekt müsahibəsinə başlamaq üzrəsiniz. 6 suala cavab verəcəksiniz. Kamera və mikrofon istifadə olunacaq.',
    bullets: [
      '6 AI tərəfindən yaradılan sual',
      'İstəğə bağlı kamera və nitq tanıma',
      'Cavablar avtomatik saxlanır',
      'Tamamlandıqdan sonra AI rəy hesabatı',
    ],
    savedDraft: 'Saxlanmış qaralama tapıldı',
    restore: 'Bərpa et',
    startFresh: '🚀 Müsahibəyə başla',
    cancel: 'Ləğv et',
    offline: 'Oflayn rejimdəsiniz. Cavablarınız yerli olaraq saxlanır.',
    question: 'Sual',
    of: '/',
    yourAnswer: 'Cavabınız',
    speakAnswer: 'Cavabınızı deyin',
    stopMicrophone: 'Danışmağı dayandırın',
    chars: 'simvol',
    starMethod: 'STAR metodu',
    previous: 'Əvvəlki',
    next: 'Növbəti sual',
    finish: 'Müsahibəni bitir',
    submitting: 'Göndərilir…',
    timeRemaining: 'Qalan vaxt',
    progress: 'İrəliləyiş',
    liveAnalytics: 'Canlı analitika',
    words: 'Söz', chars2: 'Simvol', wpm: 'SSD',
    speaking: 'Danışma', silence: 'Sükut', pauses: 'Fasilə',
    avgPause: 'Ort. Fasilə', longestPause: 'Ən uzun', avgWpm: 'Ort. SSD',
    filler: 'doldurma', fillerWord: 'söz', fillerWords: 'söz',
    microphone: 'Mikrofon', eyeContact: 'Göz təması', emotion: 'Emosiya',
    approxOnly: 'Təxmini',
    listenPlaceholder: 'Cavabınızı deyin… (əl ilə yazmaq üçün mikrofonu söndürün)',
    typePlaceholder: 'Cavabınızı yazın və ya mikrofon düyməsindən istifadə edin…',
    rec: 'YAZI',
    characters: 'Simvollar',
    cameraUnavailable: 'Kamera əlçatan deyil',
    cameraPaused: 'Kamera dayandırılıb',
    switchCamera: 'Kameranı dəyiş',
    turnCameraOff: 'Kameranı söndür',
    turnCameraOn: 'Kameranı yandır',
    live: 'CANLI',
    micPermissionDenied: 'İcazə rədd edildi',
    micNoMicrophone: 'Mikrofon tapılmadı',
    micMuted: 'Səssiz',
    micListening: 'Dinləyir',
    micSpeaking: 'Danışır',
    eyeContactOff: 'Göz təması söndürülüb',
    eyeContactLoading: 'Göz təması yüklənir…',
    lookingForward: 'İrəliyə baxır',
    lookingAway: 'Kənara baxır',
    lookingLeft: 'Sola baxır',
    lookingRight: 'Sağa baxır',
    lookingDown: 'Aşağıya baxır',
    qualityExcellent: 'Əla',
    qualityGood: 'Yaxşı',
    qualityAverage: 'Orta',
    qualityPoor: 'Zəif',
    eyeContactLabel: 'Göz təması',
    noFace: 'Üz yoxdur',
    multipleFaces: 'Bir neçə üz',
    notCentred: 'Mərkəzləşməyib',
    lookAtCamera: 'Kameraya baxın',
    emotionOff: 'Emosiya söndürülüb',
    emotionLoading: 'Emosiya yüklənir…',
    noFaceDetected: 'Üz aşkarlanmadı',
    approxVisualCue: 'təxmini vizual göstərici',
    emotionNeutral: 'Neytral', emotionHappy: 'Xoşbəxt', emotionConfident: 'Əminliklə',
    emotionNervous: 'Narahat', emotionSad: 'Kədərli', emotionAngry: 'Əsəbi',
    emotionSurprised: 'Təəccüblü', emotionDistracted: 'Diqqətsiz', emotionDetecting: 'Aşkarlanır…',
    emotionDescNeutral: 'Sakit və müvazinətli',
    emotionDescHappy: 'Müsbət və aktiv',
    emotionDescConfident: 'Özünəinamlı və aydın',
    emotionDescNervous: 'Narahat və ya qeyri-müəyyən',
    emotionDescSad: 'Aşağı enerji və ya ruhdan düşmüş',
    emotionDescAngry: 'Məyus və ya gərgin',
    emotionDescSurprised: 'Gözlənilməz vəziyyət',
    emotionDescDistracted: 'Diqqəti yayınmış',
    listeningSpeak: 'Dinləyir… cavabınızı deyin',
    starSituation: 'Vəziyyət', starTask: 'Tapşırıq', starAction: 'Fəaliyyət', starResult: 'Nəticə',
    errCameraDisconnected: 'Kamera bağlantısı kəsildi. Yenidən qoşulmağa çalışır…',
    errCameraDenied: 'Kameraya icazə verilmədi. Zəhmət olmasa brauzer parametrlərində kameraya icazə verin.',
    errCameraNotFound: 'Bu cihazda kamera tapılmadı.',
    errCameraInUse: 'Kamera artıq başqa tətbiq tərəfindən istifadə olunur.',
    errCameraGeneric: 'Kameraya giriş uğursuz oldu.',
    errMicDenied: 'Mikrofona icazə verilmədi.',
    errMicNotFound: 'Mikrofon tapılmadı.',
    errMicGeneric: 'Mikrofona giriş uğursuz oldu.',
    errSpeechNoSpeech: 'Nitq aşkarlanmadı. Yenidən cəhd edin.',
    errSpeechAudioCapture: 'Mikrofon tapılmadı.',
    errSpeechNetwork: 'Şəbəkə xətası. Bağlantınızı yoxlayın.',
    errSpeechNotAllowed: 'Mikrofona icazə verilmədi.',
    errSpeechServiceNotAllowed: 'Nitq tanınmasına icazə verilmir.',
    errSpeechLangNotSupported: 'Dil dəstəklənmir.',
    errSpeechAborted: 'Nitq tanınması dayandırıldı.',
    errSpeechMaxRestarts: 'Nitq tanınması bağlantını itirdi.',
    errSpeechStartFailed: 'Mikrofona giriş başladıla bilmədi.',
    errEyeContactUnavailable: 'Göz təması aşkarlanması əlçatan deyil.',
    errEmotionUnavailable: 'Emosiya aşkarlanması əlçatan deyil.',
    errInitFailed: 'Müsahibəni başlatmaq mümkün olmadı. Yenidən cəhd edin.',
    errStartFailed: 'Müsahibəni başlatmaq alınmadı.',
    errUnexpected: 'Müsahibə zamanı gözlənilməz xəta baş verdi.',
  },
  ru: {
    loading: 'Загрузка интервью…',
    jobNotFound: 'Вакансия не найдена. Вернитесь назад.',
    backToInterviews: 'К интервью',
    aboutToStart: 'Вы начинаете живое интервью с ИИ. Нужно ответить на 6 вопросов. Камера и микрофон будут использованы.',
    bullets: [
      '6 вопросов, сгенерированных ИИ',
      'Опциональная камера и распознавание речи',
      'Ответы сохраняются автоматически',
      'Отчёт с обратной связью по завершении',
    ],
    savedDraft: 'Найден сохранённый черновик',
    restore: 'Восстановить',
    startFresh: '🚀 Начать интервью',
    cancel: 'Отмена',
    offline: 'Вы офлайн. Ответы сохранены локально.',
    question: 'Вопрос',
    of: 'из',
    yourAnswer: 'Ваш ответ',
    speakAnswer: 'Произнесите ответ',
    stopMicrophone: 'Остановить запись',
    chars: 'симв.',
    starMethod: 'Метод STAR',
    previous: 'Назад',
    next: 'Следующий вопрос',
    finish: 'Завершить интервью',
    submitting: 'Отправка…',
    timeRemaining: 'Оставшееся время',
    progress: 'Прогресс',
    liveAnalytics: 'Аналитика',
    words: 'Слова', chars2: 'Символы', wpm: 'СЛМ',
    speaking: 'Речь', silence: 'Тишина', pauses: 'Паузы',
    avgPause: 'Ср. пауза', longestPause: 'Длиннейшая', avgWpm: 'Ср. СЛМ',
    filler: 'слов-паразитов', fillerWord: 'слово', fillerWords: 'слова',
    microphone: 'Микрофон', eyeContact: 'Зрительный контакт', emotion: 'Эмоция',
    approxOnly: 'примерно',
    listenPlaceholder: 'Произнесите ответ… (остановите микрофон для ввода текста)',
    typePlaceholder: 'Введите ответ или используйте микрофон…',
    rec: 'ЗАП',
    characters: 'Символы',
    cameraUnavailable: 'Камера недоступна',
    cameraPaused: 'Камера приостановлена',
    switchCamera: 'Сменить камеру',
    turnCameraOff: 'Выключить камеру',
    turnCameraOn: 'Включить камеру',
    live: 'ЭФИР',
    micPermissionDenied: 'Доступ запрещён',
    micNoMicrophone: 'Микрофон не найден',
    micMuted: 'Без звука',
    micListening: 'Слушает',
    micSpeaking: 'Говорит',
    eyeContactOff: 'Зрительный контакт выключен',
    eyeContactLoading: 'Загрузка зрительного контакта…',
    lookingForward: 'Смотрит вперёд',
    lookingAway: 'Отводит взгляд',
    lookingLeft: 'Смотрит влево',
    lookingRight: 'Смотрит вправо',
    lookingDown: 'Смотрит вниз',
    qualityExcellent: 'Отлично',
    qualityGood: 'Хорошо',
    qualityAverage: 'Средне',
    qualityPoor: 'Слабо',
    eyeContactLabel: 'Зрительный контакт',
    noFace: 'Нет лица',
    multipleFaces: 'Несколько лиц',
    notCentred: 'Не по центру',
    lookAtCamera: 'Смотрите в камеру',
    emotionOff: 'Эмоция выключена',
    emotionLoading: 'Загрузка эмоции…',
    noFaceDetected: 'Лицо не обнаружено',
    approxVisualCue: 'приблизительный визуальный признак',
    emotionNeutral: 'Нейтрально', emotionHappy: 'Радость', emotionConfident: 'Уверенность',
    emotionNervous: 'Волнение', emotionSad: 'Грусть', emotionAngry: 'Раздражение',
    emotionSurprised: 'Удивление', emotionDistracted: 'Отвлечён', emotionDetecting: 'Определение…',
    emotionDescNeutral: 'Спокоен и собран',
    emotionDescHappy: 'Позитивен и вовлечён',
    emotionDescConfident: 'Уверен и ясен',
    emotionDescNervous: 'Тревожен или неуверен',
    emotionDescSad: 'Низкая энергия или подавленность',
    emotionDescAngry: 'Раздражён или напряжён',
    emotionDescSurprised: 'Застигнут врасплох',
    emotionDescDistracted: 'Не сосредоточен',
    listeningSpeak: 'Слушаю… произнесите ответ',
    starSituation: 'Ситуация', starTask: 'Задача', starAction: 'Действие', starResult: 'Результат',
    errCameraDisconnected: 'Камера отключена. Попытка переподключения…',
    errCameraDenied: 'Доступ к камере запрещён. Разрешите доступ к камере в настройках браузера.',
    errCameraNotFound: 'Камера не найдена на этом устройстве.',
    errCameraInUse: 'Камера уже используется другим приложением.',
    errCameraGeneric: 'Не удалось получить доступ к камере.',
    errMicDenied: 'Доступ к микрофону запрещён.',
    errMicNotFound: 'Микрофон не найден.',
    errMicGeneric: 'Не удалось получить доступ к микрофону.',
    errSpeechNoSpeech: 'Речь не обнаружена. Попробуйте снова.',
    errSpeechAudioCapture: 'Микрофон не найден.',
    errSpeechNetwork: 'Ошибка сети. Проверьте соединение.',
    errSpeechNotAllowed: 'Доступ к микрофону запрещён.',
    errSpeechServiceNotAllowed: 'Распознавание речи запрещено.',
    errSpeechLangNotSupported: 'Язык не поддерживается.',
    errSpeechAborted: 'Распознавание речи прервано.',
    errSpeechMaxRestarts: 'Распознавание речи потеряло соединение.',
    errSpeechStartFailed: 'Не удалось получить доступ к микрофону.',
    errEyeContactUnavailable: 'Определение зрительного контакта недоступно.',
    errEmotionUnavailable: 'Определение эмоций недоступно.',
    errInitFailed: 'Не удалось инициализировать интервью. Попробуйте снова.',
    errStartFailed: 'Не удалось начать интервью.',
    errUnexpected: 'Во время интервью произошла непредвиденная ошибка.',
  },
};
